/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import {fetch} from 'frontend-js-web';

import {saveGeneratedImages} from '../../../../src/main/resources/META-INF/resources/js/AIAssistantChat/services/saveGeneratedImages';

jest.mock('frontend-js-web', () => ({fetch: jest.fn()}));

const mockFetch = fetch as jest.MockedFunction<typeof fetch>;

const IMAGE_ONE = 'data:image/png;base64,one';
const IMAGE_TWO = 'data:image/png;base64,two';

function response(ok = true) {
	return {
		blob: () => Promise.resolve(new Blob(['image'])),
		json: () => Promise.resolve({id: 1}),
		ok,
		statusText: 'Bad Request',
	};
}

describe('saveGeneratedImages', () => {
	beforeEach(() => {
		mockFetch.mockReset();
		mockFetch.mockResolvedValue(response() as never);
	});

	it('uploads a single image to the given folder tagged as AI-generated without creating a folder', async () => {
		await saveGeneratedImages([IMAGE_ONE], {folderId: 123});

		expect(
			mockFetch.mock.calls.some(([url]) =>
				String(url).endsWith('/document-folders/123/document-folders')
			)
		).toBe(false);

		const postCall = mockFetch.mock.calls.find(
			([, init]) => (init as RequestInit)?.method === 'POST'
		);

		expect(postCall?.[0]).toBe(
			'/o/headless-delivery/v1.0/document-folders/123/documents'
		);

		const formData = (postCall?.[1] as RequestInit).body as FormData;

		expect(formData.get('document')).toBe(
			JSON.stringify({keywords: ['AI-generated']})
		);
		expect(formData.get('file')).toBeInstanceOf(Blob);
	});

	it('creates an "Images Generated by AI" folder and uploads every image into it when saving multiple', async () => {
		mockFetch.mockReset();
		mockFetch.mockResolvedValueOnce({
			json: () => Promise.resolve({id: 555}),
			ok: true,
		} as never);
		mockFetch.mockResolvedValue(response() as never);

		await saveGeneratedImages([IMAGE_ONE, IMAGE_TWO], {folderId: 123});

		const folderCall = mockFetch.mock.calls.find(([url]) =>
			String(url).endsWith('/document-folders/123/document-folders')
		);

		const {name} = JSON.parse(
			(folderCall?.[1] as RequestInit).body as string
		);

		expect(name).toMatch(/^images-generated-by-ai /);

		const uploadCalls = mockFetch.mock.calls.filter(
			([url, init]) =>
				(init as RequestInit)?.method === 'POST' &&
				String(url).endsWith('/document-folders/555/documents')
		);

		expect(uploadCalls).toHaveLength(2);
	});

	it('gives each uploaded image a unique file name', async () => {
		await saveGeneratedImages([IMAGE_ONE, IMAGE_TWO], {folderId: 123});

		const fileNames = mockFetch.mock.calls
			.filter(
				([url, init]) =>
					(init as RequestInit)?.method === 'POST' &&
					String(url).endsWith('/documents')
			)
			.map(
				([, init]) =>
					((init as RequestInit).body as FormData).get('file') as File
			)
			.map((file) => file.name);

		expect(fileNames).toHaveLength(2);
		expect(new Set(fileNames).size).toBe(2);
	});

	it('falls back to the site endpoint when no folder is given', async () => {
		Liferay.ThemeDisplay.getSiteGroupId = jest.fn(() => 20124);

		await saveGeneratedImages([IMAGE_ONE], {});

		const postCall = mockFetch.mock.calls.find(
			([, init]) => (init as RequestInit)?.method === 'POST'
		);

		expect(postCall?.[0]).toBe(
			'/o/headless-delivery/v1.0/sites/20124/documents'
		);
	});

	it('throws when the upload fails', async () => {
		mockFetch.mockResolvedValueOnce(response() as never);
		mockFetch.mockResolvedValueOnce(response(false) as never);

		await expect(
			saveGeneratedImages([IMAGE_ONE], {folderId: 123})
		).rejects.toThrow('Unable to save generated image');
	});
});
